# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tract_hire', '0002_auto_20190605_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tractor',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tract_hire.Category'),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
