# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tract_hire', '0003_auto_20190605_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
