# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tract_hire', '0006_auto_20190606_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tractor_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='username',
        ),
    ]
